### ISSUE TITLE
Not an actual issue, but more a question - Multiple ELBs

### ISSUE THREAD

**Issue by jpenalosasada** [fortinet/fortigate-tutorial-gcp#4]
Can this be modified with multiple External LBs as different endpoints?

Idea is to NAT those different external endpoints to specific internal destination VMs

Thanks

**Comment by bartekmo** [comment]
Gosh, this seems to be super old - sorry. Sure, this can be done for both inbound and outbound connections. Mind that from Google Compute API perspective there's no such thing as a "load balancer", so to be precise these would be multiple forwarding rules (called "frontends" on the web console)
